spring:
  application:
    name: 'helpdesk-bff'

  cloud:
    config:
      uri: 'config-server'
    openfeign:
      okhttp:
        enabled: true

springdoc:
  openapi:
    info:
      title: 'BFF Helpdesk API'
      description: 'Component responsible for aggregating and orchestrating Helpdesk services.'
      version: '1.0.0'

eureka:
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}