spring:
  profiles:
    active: ${PROFILE_ACTIVE}

  application:
    name: 'auth-service-api'

eureka:
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI}